### ISSUE TITLE
Example data does not work with demo server

### ISSUE THREAD

**Issue by mb47** [SouthGreenPlatform/panache#24]
Hi there, 

Panache looks great -- thanks for offering this to the community!

I tried to get the demo server to work with your example data provided on the Wiki. I saved the data in the example table on the Wiki into a TSV file and tried to upload it to the demo server. The genotype tracks change from the default to B and C (what happens to A?), so this bit seems to work, but it doesn't appear to be picking up the chromosome numbers and consequently the dropdown chromosome selector is not populated with any values to choose from. 
I have attached the file I used so you can reproduce this. 

Many thanks
Micha

[panache_test.txt](https://github.com/SouthGreenPlatform/panache/files/6405493/panache_test.txt)

**Comment by SingingMeerkat** [comment]
Hi @mb47 / Micha!

Thanks for your interest and for rising this issue. The wiki is currently undergoing a lot of changes to be clearer and the table introduced in there is meant to be used as an example; it is not a real file that you could try as such with Panache. If you wish to find toy dataset to try our tool, you can find some in the 'public' folder. `miniFakeDataWithAllBlocks.tsv` for instance could be a good choice for you: it is the smallest dataset available for now and should allow you to see how Panache works with these fake data!

For a bit more detailed answer, Panache needs very specific header names, and the table in the wiki does not follow these (yet). You may be interested in the [Files & Formats](https://github.com/SouthGreenPlatform/panache/wiki/Files-&-formats) section of the wiki if you wish to see more about how the files work.

I hope this helps, please do not hesitate to tell us if it works better with the files from the `public` folder :)
I will take this opportunity to enhance the wiki section with better explanation in general and about the usable dataset, thank you for your reaching out!

Cheers
Eloi

PS: I have a little companion script to create fake files that could be used with Panache in the companionScripts folder. You could use it to try various dataset of various sizes. It is a bit old, but it is the one script I used to create my 'Fake' files originally. Headers might need to be corrected post-creation.

**Comment by mb47** [comment]
Hi Eloi,

brilliant -- that's exactly what I needed. I hadn't seen the Files & Formats link. Many thanks!

Micha

**Comment by SingingMeerkat** [comment]
Hi Micha,

Awesome! I will close this issue then, do not hesitate to reach out again if needed!

Eloi
