### ISSUE TITLE
Converting GFA file to compatible format

### ISSUE THREAD

**Issue by brettChapman** [SouthGreenPlatform/panache#30]
Hi

I have a GFA file and would like to convert to a compatible format for Panache to read in. I'm looking at using BioGraph.jl, however it isn't very clear in the documentation what exactly I need to do to get the correct format for Panache to use.

I've looked at the test_longest_path.jl in the test folder of BioGraph, but I'm not sure what the format output is supposed to be or if longest path is the correct approach to take. My GFA files are derived from PGGB. I want to use one of the references in the graph to refer to and include the GFF file from that single reference as well, including using that reference for the genomic coordinates. The way the PGGB graph was produced, no single genome was used as a reference as it was an all-to-all mapping. Thanks.

**Comment by SingingMeerkat** [comment]
Hi @brettChapman !

Somehow my notifications didn't work properly and I see this issue only now. Hopefully the discussion at [pggb issue n°158](https://github.com/pangenome/pggb/issues/158) might have helped on that subject already, with explanations about the file formats.

If it's okay with you I'll close this issue to keep everything in one place.

**Comment by SingingMeerkat** [comment]
Discussed more in detail at #32 , closing this issue.
